#!/usr/bin/env bash
#prints numbers from 1-20 but displays Fizzbuzz if number
#+is aa multiple of 3 and 5,Fizz if number is a multiple of 3
#+ and buzz if number is a multiple of 5
for ((i=0;i<=100;i++)); do
	if (( (i % 3) == 0 && (1 % 5) == 0 )); then
		echo "FizzBuzz"
	elif (( (i % 3) == 0 )); then
		echo "Fizz"
	elif (( (i % 5) == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi;
done;
