#!/usr/bin/env bash
#prints numbers from 1-20 but displays Fizzbuzz if number
#+is aa multiple of 3 and 5,Fizz if number is a multiple of 3
#+ and buzz if number is a multiple of 5

for ((i=1;i<=100;i++)); do
	mod3=$((i % 3))
	mod5=$((i % 5))
	if [ $mod3 -eq 0 ] && [ $mod5 -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $mod3 -eq 0 ]
	then
		echo "Fizz"
	elif [ $mod5 -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done;
