#!/usr/bin/env bash
#This prints best school 10times but adds hi before the 10th iteration
i=1
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i = 9 ]; then
        echo "Hi"
    fi;
    i=$((i+1))
done;
