#!/usr/bin/env bash
#This displays numbers from 1-20 printing text at 4th,9th and 17th iterations
i=1

while [ $i -le 20 ]; do
    case $i in
        4)
            echo "4"
            echo "Bad luck from China"
            ;;
        9)
            echo "9"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "Bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    i=$((i + 1))
done
